import { CANNON_BODY_TYPES } from "./constants.js";

export const DEFAULT_BASIC_RAGDOLL_BODY_PROPORTIONS = {
  shouldersDistance: 0.5,
  upperArmLength: 0.4,
  lowerArmLength: 0.4,
  armThickness: 0.2,
  neckLength: 0.1,
  headRadius: 0.25,
  upperBodyLength: 0.6,
  pelvisLength: 0.4,
  upperLegLength: 0.5,
  legThickness: 0.2,
  lowerLegLength: 0.75,
};

export const DEFAULT_BASIC_RAGDOLL_BODY_MASSES = {
  lowerLeftLeg: 1,
  lowerRightLeg: 1,
  upperLeftLeg: 1,
  upperRightLeg: 1,
  pelvis: 1,
  upperBody: 1,
  head: 0.1,
  upperLeftArm: 1,
  upperRightArm: 1,
  lowerLeftArm: 1,
  lowerRightArm: 1,
};

export const DEFAULT_BASIC_RAGDOLL_JOINT_ANGLES = {
  neck: {
    angle: Math.PI / 4,
    twistAngle: Math.PI / 8,
  },
  leftKnee: {
    angle: Math.PI / 4,
    twistAngle: Math.PI / 8,
  },
  rightKnee: {
    angle: Math.PI / 4,
    twistAngle: Math.PI / 8,
  },
  leftHip: {
    angle: Math.PI / 4,
    twistAngle: Math.PI / 8,
  },
  rightHip: {
    angle: Math.PI / 4,
    twistAngle: Math.PI / 8,
  },
  spine: {
    angle: Math.PI / 4,
    twistAngle: Math.PI / 8,
  },
  leftShoulder: {
    angle: Math.PI / 3,
    twistAngle: Math.PI / 8,
  },
  rightShoulder: {
    angle: Math.PI / 3,
    twistAngle: Math.PI / 8,
  },
  leftElbow: {
    angle: Math.PI / 4,
    twistAngle: Math.PI / 8,
  },
  rightElbow: {
    angle: Math.PI / 4,
    twistAngle: Math.PI / 8,
  },
};

export const billionaireAllBoneGroups = {
  lowerLeftLeg: ["LeftFoot", "LeftToeBase", "LeftToe_End"],
  lowerRightLeg: ["RightFoot", "RightToeBase", "RightToe_End"],
  upperLeftLeg: [],
  upperRightLeg: [],
  pelvis: ["Hips"],
  upperBody: ["Spine", "Spine1", "Spine2"],
  head: [
    "Head",
    "Neck",
    "Neck1",
    "Neck2",
    "LeftEye",
    "RightEye",
    "HeadTop_End",
  ],
  upperLeftArm: ["LeftShoulder"],
  upperRightArm: ["RightShoulder"],
  lowerLeftArm: [
    "LeftForeArm1",
    "LeftForeArm2",
    "LeftHand",
    "LeftHandThumb1",
    "LeftHandThumb2",
    "LeftHandThumb3",
    "LeftHandThumb4",
    "LeftHandIndex1",
    "LeftHandIndex2",
    "LeftHandIndex3",
    "LeftHandIndex4",
    "LeftHandMiddle1",
    "LeftHandMiddle2",
    "LeftHandMiddle3",
    "LeftHandMiddle4",
    "LeftHandRing1",
    "LeftHandRing2",
    "LeftHandRing3",
    "LeftHandRing4",
    "LeftHandPinky1",
    "LeftHandPinky2",
    "LeftHandPinky3",
    "LeftHandPinky4",
  ],
  lowerRightArm: [
    "RightForeArm1",
    "RightForeArm2",
    "RightHand",
    "RightHandThumb1",
    "RightHandThumb2",
    "RightHandThumb3",
    "RightHandThumb4",
    "RightHandIndex1",
    "RightHandIndex2",
    "RightHandIndex3",
    "RightHandIndex4",
    "RightHandMiddle1",
    "RightHandMiddle2",
    "RightHandMiddle3",
    "RightHandMiddle4",
    "RightHandRing1",
    "RightHandRing2",
    "RightHandRing3",
    "RightHandRing4",
    "RightHandPinky1",
    "RightHandPinky2",
    "RightHandPinky3",
    "RightHandPinky4",
  ],
  kneeLeft: ["LeftLeg"],
  kneeRight: ["RightLeg"],
  femurLeft: ["LeftUpLeg"],
  femurRight: ["RightUpLeg"],
  shoulderLeft: ["LeftArm"],
  shoulderRight: ["RightArm"],
  elbowLeft: ["LeftForeArm"],
  elbowRight: ["RightForeArm"],
};

export const billionaireBonesToCopyToBodies = [
  "Hips",
  "Spine1",
  "Neck2",
  "LeftLeg",
  "RightLeg",
  "LeftUpLeg",
  "RightUpLeg",
  "LeftArm",
  "RightArm",
  "LeftForeArm",
  "RightForeArm",
];

const jointRadius = 0.05;
const jointShapeType = CANNON_BODY_TYPES.SPHERE;
const limbSizeX = 0.05;
const limbSizeY = 0.05;
const limbSizeZ = 0.05;
export const billionaireRagdollBodyData = {
  lowerLeftLeg: {
    boneName: null,
    bodyType: CANNON_BODY_TYPES.CUBE,
    radius: 0,
    sizeX: limbSizeX,
    sizeY: limbSizeY * 3.25,
    sizeZ: limbSizeZ,
    mass: 0.1,
    parentBoneName: "LeftLeg",
    childBoneName: "LeftFoot",
  },
  lowerRightLeg: {
    boneName: null,
    bodyType: CANNON_BODY_TYPES.CUBE,
    radius: 0,
    sizeX: limbSizeX,
    sizeY: limbSizeY * 3.25,
    sizeZ: limbSizeZ,
    mass: 0.1,
    parentBoneName: "RightLeg",
    childBoneName: "RightFoot",
  },
  upperLeftLeg: {
    boneName: null,
    bodyType: CANNON_BODY_TYPES.CUBE,
    radius: 0,
    sizeX: limbSizeX,
    sizeY: limbSizeY * 3,
    sizeZ: limbSizeZ,
    mass: 0.15,
    parentBoneName: "LeftUpLeg",
    childBoneName: "LeftLeg",
  },
  upperRightLeg: {
    boneName: null,
    bodyType: CANNON_BODY_TYPES.CUBE,
    radius: 0,
    sizeX: limbSizeX,
    sizeY: limbSizeY * 3,
    sizeZ: limbSizeZ,
    mass: 0.15,
    parentBoneName: "RightUpLeg",
    childBoneName: "RightLeg",
  },
  pelvis: {
    boneName: "Hips",
    bodyType: jointShapeType,
    radius: 0.02,
    sizeX: 0,
    sizeY: 0,
    sizeZ: 0,
    mass: 1,
    parentBoneName: null,
    childBoneName: null,
  },
  upperBody: {
    boneName: "Spine1",
    bodyType: CANNON_BODY_TYPES.CUBE,
    radius: 0,
    sizeX: 0.1,
    sizeY: 0.23,
    sizeZ: 0.1,
    mass: 1,
    parentBoneName: null,
    childBoneName: null,
  },
  head: {
    boneName: "Neck2",
    bodyType: CANNON_BODY_TYPES.SPHERE,
    radius: 0.1,
    sizeX: 0,
    sizeY: 0,
    sizeZ: 0,
    mass: 0.25,
    parentBoneName: null,
    childBoneName: null,
  },
  upperLeftArm: {
    boneName: null,
    bodyType: CANNON_BODY_TYPES.CUBE,
    radius: 0,
    sizeX: limbSizeX,
    sizeY: limbSizeY * 1.5,
    sizeZ: limbSizeZ,
    mass: 0.1,
    parentBoneName: "LeftArm",
    childBoneName: "LeftForeArm",
  },
  upperRightArm: {
    boneName: null,
    bodyType: CANNON_BODY_TYPES.CUBE,
    radius: 0,
    sizeX: limbSizeX,
    sizeY: limbSizeY * 1.5,
    sizeZ: limbSizeZ,
    mass: 0.1,
    parentBoneName: "RightArm",
    childBoneName: "RightForeArm",
  },
  lowerLeftArm: {
    boneName: null,
    bodyType: CANNON_BODY_TYPES.CUBE,
    radius: 0,
    sizeX: limbSizeX,
    sizeY: limbSizeY * 2,
    sizeZ: limbSizeZ,
    mass: 0.2,
    parentBoneName: "LeftForeArm1",
    childBoneName: "LeftForeArm2",
  },
  lowerRightArm: {
    boneName: null,
    bodyType: CANNON_BODY_TYPES.CUBE,
    radius: 0,
    sizeX: limbSizeX,
    sizeY: limbSizeY * 2,
    sizeZ: limbSizeZ,
    mass: 0.2,
    parentBoneName: "RightForeArm1",
    childBoneName: "RightForeArm2",
  },
  kneeLeft: {
    boneName: "LeftLeg",
    bodyType: jointShapeType,
    radius: jointRadius,
    sizeX: 0,
    sizeY: 0,
    sizeZ: 0,
    mass: 0.05,
    parentBoneName: null,
    childBoneName: null,
    angle: Math.PI / 6,
    twistAngle: 0,
    jointPivotPoint: {
      x: 0.097,
      y: 0.56,
      z: 0.006726,
    },
  },
  kneeRight: {
    boneName: "RightLeg",
    bodyType: jointShapeType,
    radius: jointRadius,
    sizeX: 0,
    sizeY: 0,
    sizeZ: 0,
    mass: 0.05,
    parentBoneName: null,
    childBoneName: null,
    angle: Math.PI / 6,
    twistAngle: 0,
    jointPivotPoint: {
      x: -0.097,
      y: 0.56,
      z: 0.006726,
    },
  },
  femurLeft: {
    boneName: "LeftUpLeg",
    bodyType: jointShapeType,
    radius: jointRadius,
    sizeX: 0,
    sizeY: 0,
    sizeZ: 0,
    mass: 0.05,
    parentBoneName: null,
    childBoneName: null,
    jointPivotPoint: {
      x: 0.02,
      y: 0.93735,
      z: 0.00527,
    },
  },
  femurRight: {
    boneName: "RightUpLeg",
    bodyType: jointShapeType,
    radius: jointRadius,
    sizeX: 0,
    sizeY: 0,
    sizeZ: 0,
    mass: 0.05,
    parentBoneName: null,
    childBoneName: null,
    jointPivotPoint: {
      x: -0.02,
      y: 0.93735,
      z: 0.00527,
    },
  },
  shoulderLeft: {
    boneName: "LeftArm",
    bodyType: jointShapeType,
    radius: jointRadius,
    sizeX: 0,
    sizeY: 0,
    sizeZ: 0,
    mass: 0.05,
    parentBoneName: null,
    childBoneName: null,
    angle: Math.PI,
    twistAngle: Math.PI / 8,
    jointPivotPoint: {
      x: 0.12,
      y: 1.41,
      z: -0.0,
    },
  },
  shoulderRight: {
    boneName: "RightArm",
    bodyType: jointShapeType,
    radius: jointRadius,
    sizeX: 0,
    sizeY: 0,
    sizeZ: 0,
    mass: 0.05,
    parentBoneName: null,
    childBoneName: null,
    angle: Math.PI,
    twistAngle: Math.PI / 8,
    jointPivotPoint: {
      x: -0.12,
      y: 1.41,
      z: -0.0,
    },
  },
  elbowLeft: {
    boneName: "LeftForeArm",
    bodyType: jointShapeType,
    radius: jointRadius,
    sizeX: 0,
    sizeY: 0,
    sizeZ: 0,
    mass: 0.2,
    parentBoneName: null,
    childBoneName: null,
    jointPivotPoint: {
      x: 0.3824,
      y: 1.423,
      z: -0.05,
    },
  },
  elbowRight: {
    boneName: "RightForeArm",
    bodyType: jointShapeType,
    radius: jointRadius,
    sizeX: 0,
    sizeY: 0,
    sizeZ: 0,
    mass: 0.2,
    parentBoneName: null,
    childBoneName: null,
    jointPivotPoint: {
      x: -0.3824,
      y: 1.423,
      z: -0.05,
    },
  },
};
